//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class allexerciselist
    {
        public int allexerciseid { get; set; }
        public string Area { get; set; }
        public string Content1 { get; set; }
        public string Descriptions { get; set; }
        public string name { get; set; }
        public Nullable<int> areaid { get; set; }
    }
}
