//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class exercise
    {
        public int exerciseid { get; set; }
        public int mylistget { get; set; }
        public int usersget { get; set; }
        public string subject { get; set; }
        public string descriptions { get; set; }
        public string descriptions1 { get; set; }
        public string descriptions2 { get; set; }
        public string descriptions3 { get; set; }
        public string descriptions4 { get; set; }
        public string descriptions5 { get; set; }
        public string descriptions6 { get; set; }
        public string descriptions7 { get; set; }
        public string descriptions8 { get; set; }
        public string descriptions9 { get; set; }
        public string descriptions10 { get; set; }
        public string descriptions11 { get; set; }
        public string descriptions12 { get; set; }
        public string descriptions13 { get; set; }
        public string descriptions14 { get; set; }
        public string descriptions15 { get; set; }
        public string descriptions16 { get; set; }
        public string descriptions17 { get; set; }
        public string descriptions18 { get; set; }
        public string descriptions19 { get; set; }
        public string descriptions20 { get; set; }
        public string descriptions21 { get; set; }
        public string descriptions22 { get; set; }
        public string descriptions23 { get; set; }
        public string descriptions24 { get; set; }
        public string descriptions25 { get; set; }
        public string descriptions26 { get; set; }
        public string descriptions27 { get; set; }
        public string descriptions28 { get; set; }
        public string descriptions29 { get; set; }
        public string descriptions30 { get; set; }
        public string descriptions31 { get; set; }
        public string descriptions32 { get; set; }
        public string descriptions33 { get; set; }
        public string descriptions34 { get; set; }
        public string descriptions35 { get; set; }
        public string descriptions36 { get; set; }
        public string descriptions37 { get; set; }
        public string descriptions38 { get; set; }
        public string descriptions39 { get; set; }
        public string descriptions40 { get; set; }
        public string descriptions41 { get; set; }
        public string descriptions42 { get; set; }
        public string descriptions43 { get; set; }
        public string descriptions44 { get; set; }
        public string descriptions45 { get; set; }
        public string descriptions46 { get; set; }
        public string descriptions47 { get; set; }
        public string descriptions48 { get; set; }
        public string descriptions49 { get; set; }
        public string descriptions50 { get; set; }
        public string descriptions51 { get; set; }
        public string descriptions52 { get; set; }
        public string descriptions53 { get; set; }
        public string descriptions54 { get; set; }
        public string descriptions55 { get; set; }
        public string descriptions56 { get; set; }
        public string descriptions57 { get; set; }
        public string descriptions58 { get; set; }
        public string descriptions59 { get; set; }
        public string descriptions60 { get; set; }
        public string descriptions61 { get; set; }
        public string descriptions62 { get; set; }
        public string descriptions63 { get; set; }
        public string descriptions64 { get; set; }
        public string descriptions65 { get; set; }
        public string descriptions66 { get; set; }
        public string descriptions67 { get; set; }
        public string descriptions68 { get; set; }
        public string descriptions69 { get; set; }
        public string descriptions70 { get; set; }
        public string descriptions71 { get; set; }
        public string descriptions72 { get; set; }
        public string descriptions73 { get; set; }
        public string descriptions74 { get; set; }
        public string descriptions75 { get; set; }
        public string descriptions76 { get; set; }
        public string descriptions77 { get; set; }
        public string descriptions78 { get; set; }
        public string descriptions79 { get; set; }
        public string descriptions80 { get; set; }
        public string descriptions81 { get; set; }
        public string descriptions82 { get; set; }
        public string descriptions83 { get; set; }
        public string descriptions84 { get; set; }
        public string descriptions85 { get; set; }
        public string descriptions86 { get; set; }
        public string descriptions87 { get; set; }
        public string descriptions88 { get; set; }
        public string descriptions89 { get; set; }
        public string descriptions90 { get; set; }
        public string descriptions91 { get; set; }
        public string descriptions92 { get; set; }
        public string descriptions93 { get; set; }
        public string descriptions94 { get; set; }
        public string descriptions95 { get; set; }
        public string descriptions96 { get; set; }
        public string descriptions97 { get; set; }
        public string descriptions98 { get; set; }
        public string descriptions99 { get; set; }
        public string descriptions100 { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }
        public string content1 { get; set; }
        public string content2 { get; set; }
        public string content3 { get; set; }
        public string content4 { get; set; }
        public string content5 { get; set; }
        public string content6 { get; set; }
        public string content7 { get; set; }
        public string content8 { get; set; }
        public string content9 { get; set; }
        public string content10 { get; set; }
        public string content11 { get; set; }
        public string content12 { get; set; }
        public string content13 { get; set; }
        public string content14 { get; set; }
        public string content15 { get; set; }
        public string content16 { get; set; }
        public string content17 { get; set; }
        public string content18 { get; set; }
        public string content19 { get; set; }
        public string content20 { get; set; }
        public string content21 { get; set; }
        public string content22 { get; set; }
        public string content23 { get; set; }
        public string content24 { get; set; }
        public string content25 { get; set; }
        public string content26 { get; set; }
        public string content27 { get; set; }
        public string content28 { get; set; }
        public string content29 { get; set; }
        public string content30 { get; set; }
        public string content31 { get; set; }
        public string content32 { get; set; }
        public string content33 { get; set; }
        public string content34 { get; set; }
        public string content35 { get; set; }
        public string content36 { get; set; }
        public string content37 { get; set; }
        public string content38 { get; set; }
        public string content39 { get; set; }
        public string content40 { get; set; }
        public string content41 { get; set; }
        public string content42 { get; set; }
        public string content43 { get; set; }
        public string content44 { get; set; }
        public string content45 { get; set; }
        public string content46 { get; set; }
        public string content47 { get; set; }
        public string content48 { get; set; }
        public string content49 { get; set; }
        public string content50 { get; set; }
        public string content51 { get; set; }
        public string content52 { get; set; }
        public string content53 { get; set; }
        public string content54 { get; set; }
        public string content55 { get; set; }
        public string content56 { get; set; }
        public string content57 { get; set; }
        public string content58 { get; set; }
        public string content59 { get; set; }
        public string content60 { get; set; }
        public string content61 { get; set; }
        public string content62 { get; set; }
        public string content63 { get; set; }
        public string content64 { get; set; }
        public string content65 { get; set; }
        public string content66 { get; set; }
        public string content67 { get; set; }
        public string content68 { get; set; }
        public string content69 { get; set; }
        public string content70 { get; set; }
        public string content71 { get; set; }
        public string content72 { get; set; }
        public string content73 { get; set; }
        public string content74 { get; set; }
        public string content75 { get; set; }
        public string content76 { get; set; }
        public string content77 { get; set; }
        public string content78 { get; set; }
        public string content79 { get; set; }
        public string content80 { get; set; }
        public string content81 { get; set; }
        public string content82 { get; set; }
        public string content83 { get; set; }
        public string content84 { get; set; }
        public string content85 { get; set; }
        public string content86 { get; set; }
        public string content87 { get; set; }
        public string content88 { get; set; }
        public string content89 { get; set; }
        public string content90 { get; set; }
        public string content91 { get; set; }
        public string content92 { get; set; }
        public string content93 { get; set; }
        public string content94 { get; set; }
        public string content95 { get; set; }
        public string content96 { get; set; }
        public string content97 { get; set; }
        public string content98 { get; set; }
        public string content99 { get; set; }
        public string content100 { get; set; }
    
        public virtual mylist mylist { get; set; }
        public virtual users users { get; set; }
    }
}
