//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlineptEntities : DbContext
    {
        public onlineptEntities()
            : base("name=onlineptEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<allexerciselist> allexerciselist { get; set; }
        public DbSet<events> events { get; set; }
        public DbSet<exercise> exercise { get; set; }
        public DbSet<home> home { get; set; }
        public DbSet<homework> homework { get; set; }
        public DbSet<messagebox> messagebox { get; set; }
        public DbSet<myconnect> myconnect { get; set; }
        public DbSet<mylist> mylist { get; set; }
        public DbSet<mymessage> mymessage { get; set; }
        public DbSet<mynotification> mynotification { get; set; }
        public DbSet<myquestions> myquestions { get; set; }
        public DbSet<nutrition> nutrition { get; set; }
        public DbSet<onlinecourse> onlinecourse { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<sendusersanalysis> sendusersanalysis { get; set; }
        public DbSet<student> student { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<yuklenenbelgeler> yuklenenbelgeler { get; set; }
    }
}
