//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class myconnect
    {
        public int myconnectid { get; set; }
        public int usersget { get; set; }
        public string namesurname { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public string youremail { get; set; }
        public string subject { get; set; }
        public string descriptions { get; set; }
        public string color { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }
		
		public string Body { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
