//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mylist
    {
        public mylist()
        {
            this.exercise = new HashSet<exercise>();
            this.home = new HashSet<home>();
            this.homework = new HashSet<homework>();
            this.mymessage = new HashSet<mymessage>();
            this.mynotification = new HashSet<mynotification>();
            this.myquestions = new HashSet<myquestions>();
            this.nutrition = new HashSet<nutrition>();
            this.onlinecourse = new HashSet<onlinecourse>();
            this.payment = new HashSet<payment>();
            this.sendusersanalysis = new HashSet<sendusersanalysis>();
            this.student = new HashSet<student>();
        }
    
        public int mylistid { get; set; }
        public int usersget { get; set; }
        public string listname { get; set; }
    
        public virtual ICollection<exercise> exercise { get; set; }
        public virtual ICollection<home> home { get; set; }
        public virtual ICollection<homework> homework { get; set; }
        public virtual ICollection<mymessage> mymessage { get; set; }
        public virtual ICollection<mynotification> mynotification { get; set; }
        public virtual ICollection<myquestions> myquestions { get; set; }
        public virtual ICollection<nutrition> nutrition { get; set; }
        public virtual ICollection<onlinecourse> onlinecourse { get; set; }
        public virtual ICollection<payment> payment { get; set; }
        public virtual ICollection<sendusersanalysis> sendusersanalysis { get; set; }
        public virtual ICollection<student> student { get; set; }
    }
}
