//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
		
    
    public partial class mynotification
    {
        public int mynotificationid { get; set; }
        public int usersget { get; set; }
        public int mylistget { get; set; }
        public string mynotification1 { get; set; }
        public string color { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }

        public virtual mylist mylist { get; set; }
        public virtual users users { get; set; }
    }
}
