//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
		
    
    public partial class payment
    {
        public int paymentid { get; set; }
        public int mylistget { get; set; }
        public int usersget { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }
        public string pay1 { get; set; }
        public string pay2 { get; set; }
        public string pay3 { get; set; }
        public string pay4 { get; set; }
        public string pay5 { get; set; }
        public string pay6 { get; set; }
        public string pay7 { get; set; }
        public string pay8 { get; set; }
        public string pay9 { get; set; }
        public string pay10 { get; set; }
        public string pay11 { get; set; }
        public string pay12 { get; set; }
        public string total { get; set; }
    
        public virtual mylist mylist { get; set; }
        public virtual users users { get; set; }
    }
}
