//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class student
    {
		public int viewkey { get; set; }
        public int studentid { get; set; }
        public int mylistget { get; set; }
        public int usersget { get; set; }
        public string gender { get; set; }
        public string weight { get; set; }
        public string height { get; set; }
        public string age { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }
        public string bodyfat { get; set; }
        public string bodymuscle { get; set; }
        public string neck { get; set; }
        public string shoulder { get; set; }
        public string chest { get; set; }
        public string larm { get; set; }
        public string lfarm { get; set; }
        public string rarm { get; set; }
        public string rfarm { get; set; }
        public string waist { get; set; }
        public string hip { get; set; }
        public string lleg { get; set; }
        public string lcalves { get; set; }
        public string rleg { get; set; }
        public string rcalves { get; set; }
        public string calori { get; set; }
        public string protein { get; set; }
        public string carb { get; set; }
        public string fat { get; set; }		
		public string inseam { get; set; }
		public string fatneck { get; set; }
		public string fatlarm { get; set; }
		public string fatrarm { get; set; }
		public string fatbody { get; set; }
		public string fatlleg { get; set; }
		public string fatrleg { get; set; }		
        public string caloriedeficit { get; set; }
        public virtual HttpPostedFileBase content1file { get; set; }
        public string content1 { get; set; }
        public virtual HttpPostedFileBase content2file { get; set; }
        public string content2 { get; set; }
        public virtual HttpPostedFileBase content3file { get; set; }
        public string content3 { get; set; }
    
        public virtual mylist mylist { get; set; }
        public virtual users users { get; set; }
    }
}
