//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinept.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class users
    {
        public users()
        {
            this.exercise = new HashSet<exercise>();
            this.home = new HashSet<home>();
            this.homework = new HashSet<homework>();
            this.mymessage = new HashSet<mymessage>();
            this.mynotification = new HashSet<mynotification>();
            this.myquestions = new HashSet<myquestions>();
            this.nutrition = new HashSet<nutrition>();
            this.onlinecourse = new HashSet<onlinecourse>();
            this.payment = new HashSet<payment>();
            this.sendusersanalysis = new HashSet<sendusersanalysis>();
            this.student = new HashSet<student>();
        }
        [Required(ErrorMessage = "Otomatik Kullanıcı Seçimi Tespit Edildi.Güvenlik nedeniyle Lütfen Kullanıcı Adınızı Yazarak Giriş Yapınız!")]
        public int userid { get; set; }
		public int viewkey { get; set; }
        public int roleid { get; set; }
        public int viewmylist { get; set; }
        public string active { get; set; }
        public virtual HttpPostedFileBase profilephotoFile { get; set; }
        public string profilephoto { get; set; }
        public string name { get; set; }
        [Required(ErrorMessage = "Lütfen Kullanıcı Adınızı Giriniz!")]
        public string usrname { get; set; }
        [Required(ErrorMessage = "Lütfen Parolanızı Giriniz!")]
        public string password { get; set; }
        public string email { get; set; }
        public string tc { get; set; }
        public string tel { get; set; }
        public string role { get; set; }
        public string gender { get; set; }
        public string securitykey { get; set; }
        public string fgTo { get; set; }
        public string fgSubject { get; set; }
        public string fgBody { get; set; }
        public string fgEmail { get; set; }
        public string fgPassword { get; set; }
        public int mylistid { get; set; }
        public int usersget { get; set; }
        public string listname { get; set; }

        public virtual ICollection<exercise> exercise { get; set; }
        public virtual ICollection<home> home { get; set; }
        public virtual ICollection<homework> homework { get; set; }
        public virtual ICollection<mymessage> mymessage { get; set; }
        public virtual ICollection<mynotification> mynotification { get; set; }
        public virtual ICollection<myquestions> myquestions { get; set; }
        public virtual ICollection<nutrition> nutrition { get; set; }
        public virtual ICollection<onlinecourse> onlinecourse { get; set; }
        public virtual ICollection<payment> payment { get; set; }
        public virtual ICollection<sendusersanalysis> sendusersanalysis { get; set; }
        public virtual ICollection<student> student { get; set; }
    }
}
